### ISSUE TITLE
Renaming import, cause it to rename in the cached source file as well

### ISSUE THREAD

**Issue by ariaandika** [rust-lang/rust-analyzer#17318]
**rust-analyzer version**: from `rust-analyzer -V`: `rust-analyzer 0.3.1975-standalone`, from nvim mason `installed version 2024-05-27`

**rustc version**: `rustc 1.78.0 (9b00956e5 2024-04-29)`

**editor or extension**: `nvim --version`: `NVIM v0.10.0`

**relevant settings**: RUSTC_WRAPPER=sccache

**step to reproduce**: 
`cargo init`

`cargo add axum`

```rust
use axum::response::Html;

fn main() {
    let app = Html("awd");
}
```

then use "rename" (F2), in `use axum::response::Html`

```rust
use axum::response::Html as HtmlRespone;

fn main() {
    let app = HtmlRespone("awd");
}
```

`rm -rf ./target/`, because its not affect this project that use source in `./target/`, instead its affect other new project that uses cache in `~/.cargo/registry/src`

`cargo build`

```bash
error[E0412]: cannot find type `HtmlResponse` in this scope
   --> /home/deuzo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/axum-0.7.5/src/response/mod.rs:41:26
    |
41  | impl<T> IntoResponse for HtmlResponse<T>
    |                          ^^^^^^^^^^^^ help: a trait with a similar name exists: `IntoResponse`
    |
   ::: /home/deuzo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/axum-core-0.4.3/src/response/into_response.rs:112:1
    |
112 | pub trait IntoResponse {
    | ---------------------- similarly named trait `IntoResponse` defined here

error[E0412]: cannot find type `HtmlResponse` in this scope
   --> /home/deuzo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/axum-0.7.5/src/response/mod.rs:57:21
    |
57  | impl<T> From<T> for HtmlResponse<T> {
    |                     ^^^^^^^^^^^^ help: a trait with a similar name exists: `IntoResponse`
    |
   ::: /home/deuzo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/axum-core-0.4.3/src/response/into_response.rs:112:1
    |
112 | pub trait IntoResponse {
    | ---------------------- similarly named trait `IntoResponse` defined here

For more information about this error, try `rustc --explain E0412`.
error: could not compile `axum` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
```

the source file in cache renamed

also when i 'write all' in neovim, it shows that it writen file inside `~/.cargo` directory

**Comment by Veykril** [comment]
Broke in https://github.com/rust-lang/rust-analyzer/pull/16489
