### ISSUE TITLE
FP syntax error `use std::fmt::self;`

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust-analyzer#23000]
```rust
use std::fmt::self;
fn main () {}
```
this compiles but ra diagnostics say
```
at crate ra, file /tmp/ra/src/main.rs: Error SyntaxError from LineCol { line: 0, col: 14 } to LineCol { line: 0, col: 18 }: Syntax Error: The `self` keyword is only allowed as the first segment of a path
```

**Comment by A4-Tacks** [comment]
> this compiles

This is fake

```
error[E0429]: `self` imports are only allowed within a { } list
 --> src/bin/main.rs:1:13
  |
1 | use std::fmt::self;
  |             ^^^^^^
  |
```

**Comment by matthiaskrgr** [comment]
I can't reproduce your error on the rust playground
https://play.rust-lang.org/?version=stable&mode=release&edition=2024&gist=1f160b620a6caa58c13131fac56751fa

**Comment by A4-Tacks** [comment]
> Build using the Stable version: 1.97.1

I host use `rustc 1.97.0-nightly (36ba2c771 2026-04-23)`

In 1.97.0 release log:

> [Allow trailing self in imports in more cases](https://github.com/rust-lang/rust/pull/155137)

Oh, ok
