### ISSUE TITLE
Weird `'static` requirement

### ISSUE THREAD

**Issue by Kiwifuit** [rust-lang/rust-analyzer#18088]
**rust-analyzer version**: (eg. output of "rust-analyzer: Show RA Version" command, accessible in VSCode via <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>)
0.3.2104-standalone

**rustc version**: (eg. output of `rustc -V`)
rustc 1.81.0 (eeb90cda1 2024-09-04)

**editor or extension**: (eg. VSCode, Vim, Emacs, etc. For VSCode users, specify your extension version; 
for users of other editors, provide the distribution if applicable)
VSCode with the official extension (`rust-lang.rust-analyzer`)

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTC`, `RUSTUP_HOME` or `CARGO_HOME`)

**repository link (if public, optional)**: (eg. [rust-analyzer](https://github.com/rust-lang/rust-analyzer))
[this specific spot](https://github.com/Kiwifuit/DMS/blob/mcs/sec-update-dependencies/denji/examples/install-server.rs#L18-L24)

**code snippet to reproduce**: 
```rust
// I've already pushed the bad change, but here it is:
// L18 - L24
    let temp_dir = TempDir::new().unwrap();
    let server_installer = MinecraftServer::new(
        ServerSoftware::Forge,
        "1.20.4-49.1.4",
        "1.20.4",
        temp_dir.path(),
    );
```
Produces this error:
```
error[E0597]: `temp_dir` does not live long enough
  --> denji/examples/install-server.rs:23:9
   |
18 |     let temp_dir = TempDir::new().unwrap();
   |         -------- binding `temp_dir` declared here
...
23 |         temp_dir.path(),
   |         ^^^^^^^^-------
   |         |
   |         borrowed value does not live long enough
   |         argument requires that `temp_dir` is borrowed for `'static`
...
52 | }
   | - `temp_dir` dropped here while still borrowed
```
That does not appear with `cargo check` or `cargo clippy`. Running `grep -HrnIiF "'static" --include "*.rs"` on my and [the `temp-dir` crate's](https://gitlab.com/leonhard-llc/ops/-/tree/main)'s repositories yield no relevant results

**Comment by flodiebold** [comment]
This error comes from rustc, RA doesn't produce borrow checker errors yet, so this has to be a matter of the features or env variables you run cargo check with.

**Comment by flodiebold** [comment]
The error is in an example, that's why you don't see it with bare `cargo check`. `cargo check --examples` (or `--all-targets`, which is what RA does) shows it.

**Comment by flodiebold** [comment]
As for the error, if I'm reading it correctly the `'static` requirement comes from moving the `server_installer` into the async block which gets `spawn`ed (`spawn` requires that the closure you give it be `'static`). One easy way to fix it is to make the path owned e.g. using `temp_dir.path().to_owned()`.
