### PR TITLE
Require rust 1.81

### PR DESCRIPTION
**Pull request by darichey**
rust-analyzer doesn't build on 1.80 because we use `#[expect(lint)]`:
```
error[E0658]: the `#[expect]` attribute is an experimental feature
  --> crates/hir-expand/src/prettify_macro_expansion_.rs:11:1
   |
11 | #[expect(deprecated)]
   | ^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #54503 <https://github.com/rust-lang/rust/issues/54503> for more information
```

### CODE REVIEW

**Comment by lnicola** [comment]
@ChayimFriedman2 think we can switch that to `allow`? 1.81 is still relatively recent, and we've had complaints before. Also, is the trailing `_` intended?

**Comment by ChayimFriedman2** [comment]
> @ChayimFriedman2 think we can switch that to `allow`? 1.81 is still relatively recent, and we've had complaints before

I thought our policy is to support latest stable version, but if this is a problem, yes we can switch that to `#[allow]`.

> Also, is the trailing `_` intended?

Yes, it's because we import the function with the same name from the module (and only export it), so they need to have different names.

**Comment by lnicola** [comment]
> I thought our policy is to support latest stable version

On paper yes, but we're been less strict in the past. But I guess it's been three days and nobody complained yet so..

@bors r+

**Comment by Wilfred** [comment]
> On paper yes, but we're been less strict in the past. But I guess it's been three days and nobody complained yet so..

@lnicola as a data point, it takes us ~1 month to upgrade to the latest stable, so slightly less aggressive MSRV would be helpful for us to run the latest r-a and collaborate with y'all :)

**Comment by lnicola** [comment]
> it takes us ~1 month to upgrade to the latest stable, so slightly less aggressive MSRV would be helpful for us to run the latest r-a

Noted.

> fortunately r-a doesn't use any 1.82 features despite the MSRV bump

What do you mean? Does #18256 work on 1.81?

**Comment by Wilfred** [comment]
Argh, I'd configured rustup incorrectly. You're right, recent commits no longer builds on 1.81.

**Comment by lnicola** [comment]
I see. Do you want us to revert it?

**Comment by Wilfred** [comment]
Thanks for the kind offer, but we should be on 1.82 in around a week, so it's not worth it I think. We'll run 26d2fbaef2d68a2fccf55d725915188c2634439a (the last commit that compiles with 1.81) until then.
