### PR TITLE
vscode: fix extraEnv handling numeric values

### LINKED ISSUE #12363: rust-analyzer fails to start with inexplicable error when a non-string value is specified in `rust-analyzer.server.extraEnv`
This used to work, but I think it broke in #12215 

```json
  "rust-analyzer.server.extraEnv": {
    "CHALK_OVERFLOW_DEPTH": 500,
  },
```

This setting in vscode's settings.json causes r-a to fail to start with the following error:

```
[2022-05-23 19:59:13.330] [exthost] [error] TypeError: r[c].value.replace is not a function
	at wm (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.3.1066/out/main.js:40:18181)
	at Tm (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.3.1066/out/main.js:40:19206)
	at Function.create (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.3.1066/out/main.js:82:3936)
	at IS (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.3.1066/out/main.js:84:1309)
	at async pv (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.3.1066/out/main.js:84:641)
	at async _activate (/home/discord/.vscode-server-insiders/bin/688c80245936b49b7ceca494d9edfe97cae06f8a/out/vs/workbench/api/node/extensionHostProcess.js:83:8180)
	at async _waitForDepsThenActivate (/home/discord/.vscode-server-insiders/bin/688c80245936b49b7ceca494d9edfe97cae06f8a/out/vs/workbench/api/node/extensionHostProcess.js:83:8122)
	at async _initialize (/home/discord/.vscode-server-insiders/bin/688c80245936b49b7ceca494d9edfe97cae06f8a/out/vs/workbench/api/node/extensionHostProcess.js:83:7486
```
	
It would be nice if we could throw a better error here, or define the type of the object so that a user can more readily identify this error if they encounter it.

### PR DESCRIPTION
**Pull request by jhgg**
fixes #12363 by bringing the types more inline with the reality, and making `Env` not a lie.

### CODE REVIEW

**Comment by jhgg** [comment]
Need to figure out how to get prettier to run here.

File: editors/code/src/config.ts [hunk 1]
```diff
@@ -100,8 +100,12 @@ export class Config {
     get serverPath() {
         return this.get<null | string>("server.path") ?? this.get<null | string>("serverPath");
     }
-    get serverExtraEnv() {
-        return this.get<Env | null>("server.extraEnv") ?? {};
+    get serverExtraEnv(): Env {
+        const extraEnv =
+            this.get<{ [key: string]: string | number } | null>("server.extraEnv") ?? {};
+        return Object.fromEntries(
```
Comment (lnicola) [inline editors/code/src/config.ts:106]: I suppose there must be a way to only change the values that aren't strings, but it doesn't really matter here.
