### ISSUE TITLE
rust-analyzer fails to start with inexplicable error when a non-string value is specified in `rust-analyzer.server.extraEnv`

### ISSUE THREAD

**Issue by jhgg** [rust-lang/rust-analyzer#12363]
This used to work, but I think it broke in #12215 

```json
  "rust-analyzer.server.extraEnv": {
    "CHALK_OVERFLOW_DEPTH": 500,
  },
```

This setting in vscode's settings.json causes r-a to fail to start with the following error:

```
[2022-05-23 19:59:13.330] [exthost] [error] TypeError: r[c].value.replace is not a function
	at wm (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.3.1066/out/main.js:40:18181)
	at Tm (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.3.1066/out/main.js:40:19206)
	at Function.create (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.3.1066/out/main.js:82:3936)
	at IS (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.3.1066/out/main.js:84:1309)
	at async pv (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.3.1066/out/main.js:84:641)
	at async _activate (/home/discord/.vscode-server-insiders/bin/688c80245936b49b7ceca494d9edfe97cae06f8a/out/vs/workbench/api/node/extensionHostProcess.js:83:8180)
	at async _waitForDepsThenActivate (/home/discord/.vscode-server-insiders/bin/688c80245936b49b7ceca494d9edfe97cae06f8a/out/vs/workbench/api/node/extensionHostProcess.js:83:8122)
	at async _initialize (/home/discord/.vscode-server-insiders/bin/688c80245936b49b7ceca494d9edfe97cae06f8a/out/vs/workbench/api/node/extensionHostProcess.js:83:7486
```
	
It would be nice if we could throw a better error here, or define the type of the object so that a user can more readily identify this error if they encounter it.

**Comment by Veykril** [comment]
The line that throws is this one https://github.com/rust-lang/rust-analyzer/blob/81805d4cfc2bb307d911806dffb6eabf29b623e3/editors/code/src/config.ts#L303
So the problem is that the code assumes everything to be strings, which is obviously not the case. We should probably filter out all non string keys and just add them to the result at the end as is since they don't have any substitutions.

cc @listochkin not sure if you have time to fix this this week

**Comment by jhgg** [comment]
We could just coerce the value to a string always. That would be a quick one line fix.
